create extension if not exists pgcrypto;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  stripe_session_id text unique not null,
  status text not null default 'pending' check (status in ('pending', 'paid', 'cancelled', 'fulfilled')),
  total_cents integer not null check (total_cents >= 0),
  items jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text unique not null,
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;
alter table public.subscribers enable row level security;
